import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {chromium} from '@playwright/test';
test('panels own contextual commands in both windows',{timeout:90000},async t=>{
 const base='http://127.0.0.1:5213',server=spawn(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port','5213','--strictPort'],{stdio:'pipe',windowsHide:true});t.after(()=>server.kill());for(let i=0;i<100;i++){try{if((await fetch(base)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const browser=await chromium.launch({channel:'msedge',headless:true});t.after(()=>browser.close());const context=await browser.newContext({permissions:['clipboard-read','clipboard-write'],viewport:{width:1400,height:950}}),page=await context.newPage(),errors=[];context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.waitForFunction(()=>document.querySelector('#state')?.textContent==='実行できます',null,{timeout:60000});
 const menu=page.locator('.panel-context-menu');const file=page.locator('#file-list button[title="src/Main.jal"]');await file.click({button:'right'});assert.deepEqual(await menu.getByRole('menuitem').allTextContents(),['開く','新規 JAL ファイル…','名前を変更…','移動…','相対パスをコピー']);await menu.getByText('相対パスをコピー',{exact:true}).click();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'src/Main.jal');
 const folder=page.locator('#file-list summary').first();await folder.click({button:'right'});await menu.getByText('折りたたむ',{exact:true}).click();assert.equal(await folder.evaluate(n=>n.parentElement.open),false);await folder.focus();await page.keyboard.press('Shift+F10');await menu.getByText('展開する',{exact:true}).click();assert.equal(await folder.evaluate(n=>n.parentElement.open),true);
 await page.locator('.view-line').first().click({button:'right'});await page.locator('.monaco-menu-container').waitFor();await page.keyboard.press('Escape');
 await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#state')?.textContent==='実行が完了しました');await page.locator('#output').click({button:'right'});assert.equal(await menu.getByText('選択範囲をコピー',{exact:true}).isDisabled(),true);await menu.getByText('出力をすべてコピー',{exact:true}).click();assert.equal((await page.evaluate(()=>navigator.clipboard.readText())).replaceAll('\r\n','\n'),'Hello, World!\n');await page.locator('#output').click({button:'right'});await menu.getByText('コンソールを消去',{exact:true}).click();assert.equal(await page.locator('#output').textContent(),'');
 await page.locator('#instructions-tab').click();await page.locator('.instruction-detail h2').click({button:'right'});assert.equal(await menu.getByText('コンソールを消去',{exact:true}).count(),0);await page.screenshot({path:'.cache/context-menu-instructions.png'});await menu.getByText('命令名をコピー',{exact:true}).click();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'iadd');
 await page.locator('.instruction-detail h2').click({button:'right'});await menu.getByText('命令を検索',{exact:true}).click();assert.equal(await page.getByRole('searchbox',{name:'命令を検索'}).getAttribute('aria-expanded'),'true');
 const event=page.waitForEvent('popup');await page.locator('#instructions-tab').click({button:'right'});await menu.getByText('小窓で開く',{exact:true}).click();const popup=await event;await popup.locator('.instruction-detail h2').click({button:'right'});const popupMenu=popup.locator('.panel-context-menu');await popupMenu.getByText('書き方の例をコピー',{exact:true}).click();assert.match(await popup.evaluate(()=>navigator.clipboard.readText()),/iadd/);await popup.getByRole('tab',{name:'Instructions',exact:true}).click({button:'right'});assert.deepEqual(await popupMenu.getByRole('menuitem').allTextContents(),['このタブを閉じる','他のタブを閉じる']);await popup.keyboard.press('Escape');await popup.close();
 await page.evaluate(async()=>{const {editor}=await import('/src/main.ts');editor.setValue('public class Main {\n public static main([Ljava/lang/String;)V {\n bipush 1\n pop\n return\n }\n}');});await page.locator('#problems-tab').click();await page.locator('#problems li button').first().waitFor();await page.locator('#problems li button').first().click({button:'right'});assert.deepEqual(await menu.getByRole('menuitem').allTextContents(),['ソースへ移動','この問題をコピー','問題をすべてコピー']);await menu.getByText('ソースへ移動',{exact:true}).click();assert.equal(await page.evaluate(async()=>(await import('/src/main.ts')).editor.getPosition().lineNumber),3);
 await file.focus();await page.keyboard.press('Shift+F10');await page.keyboard.press('ArrowDown');await page.keyboard.press('Escape');assert.equal(await menu.count(),0);assert.equal(await file.evaluate(n=>n===document.activeElement),true);assert.deepEqual(errors,[]);
});
