import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {readFile} from 'node:fs/promises';import {unzipSync} from 'fflate';import {chromium} from '@playwright/test';
test('bundled PrintStream, System and ArrayList disassemble and graphs without receiver errors or drag selection',{timeout:240000},async t=>{
 const base='http://127.0.0.1:5226',server=spawn(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port','5226','--strictPort'],{stdio:'pipe',windowsHide:true});t.after(()=>server.kill());
 for(let i=0;i<100;i++){try{if((await fetch(base)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const browser=await chromium.launch({channel:'msedge',headless:true});t.after(()=>browser.close());const page=await browser.newPage();page.setDefaultTimeout(120000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.layoutCalls=0;const post=Worker.prototype.postMessage;Worker.prototype.postMessage=function(message,...args){if(message?.path?.includes('positionGraphs'))window.layoutCalls++;return post.call(this,message,...args);};});await page.goto(base);await page.waitForFunction(()=>document.querySelector('#state')?.textContent==='実行できます');
 for(const [name,methods,nodes] of [['PrintStream',71,1322],['System',39,849],['ArrayList',68,1533]]){
 await page.evaluate(()=>{window.graphProgressSeen={outline:false,partial:false,stepped:false};const observer=new MutationObserver(()=>{const pending=document.querySelectorAll('.graph-method-progress'),nodes=document.querySelectorAll('.graph-node');if(pending.length&&!nodes.length)window.graphProgressSeen.outline=true;if(pending.length&&nodes.length)window.graphProgressSeen.partial=true;if([...pending].some(p=>Number(p.getAttribute('aria-valuenow'))>0))window.graphProgressSeen.stepped=true;});observer.observe(document.body,{subtree:true,childList:true,attributes:true});window.graphProgressObserver=observer;});
 const entry='java/'+(name==='System'?'lang':name==='ArrayList'?'util':'io')+'/'+name+'.class';
 const bytes=unzipSync(await readFile('public/runtime/jdk23.jar'),{filter:file=>file.name===entry})[entry];assert.ok(bytes);
 await page.evaluate(({bytes,name})=>{const dt=new DataTransfer();dt.items.add(new File([new Uint8Array(bytes)],name+'.class'));window.dispatchEvent(new DragEvent('drop',{dataTransfer:dt,bubbles:true,cancelable:true}));},{bytes:Array.from(bytes),name});
 await page.waitForFunction(()=>document.querySelector('#state')?.textContent.includes('逆アセンブルしました'));await page.locator('#graph-tab').click();await page.waitForFunction(({methods,nodes})=>document.querySelectorAll('.graph-method').length===methods&&document.querySelectorAll('.graph-node').length===nodes,{methods,nodes});
 const progress=await page.evaluate(()=>{window.graphProgressObserver.disconnect();return window.graphProgressSeen;});assert.deepEqual(progress,{outline:true,partial:true,stepped:true});assert.match(await page.locator('.graph-status').innerText(),/100%/);assert.doesNotMatch(await page.locator('#output').innerText(),/JALWEB_PROGRESS/);
 assert.equal(await page.locator('.graph-node text').first().evaluate(el=>getComputedStyle(el).userSelect),'none');
 const box=await page.locator('.graph-canvas').boundingBox();const before=await page.locator('.graph-canvas>g').getAttribute('transform');await page.evaluate(()=>getSelection()?.removeAllRanges());await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+80,box.y+box.height/2+40,{steps:8});await page.mouse.up();assert.equal(await page.evaluate(()=>getSelection()?.toString()),'');assert.notEqual(await page.locator('.graph-canvas>g').getAttribute('transform'),before);assert.deepEqual(errors,[]);
 }
 const count=await page.evaluate(()=>window.layoutCalls);await page.getByRole('tab',{name:/PrintStream/}).click();await page.waitForFunction(()=>document.querySelectorAll('.graph-node').length===1322);assert.equal(await page.evaluate(()=>window.layoutCalls),count);assert.equal(await page.locator('.graph-method-progress').count(),0);assert.match(await page.locator('.graph-status').innerText(),/100%/);
});
