import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {chromium} from '@playwright/test';
test('Alt hover compares nearby frames, shows only changed locals, and works in detached windows',{timeout:90000},async t=>{
 const server=spawn(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port','5193','--strictPort'],{stdio:'pipe',windowsHide:true});t.after(()=>server.kill());const base='http://127.0.0.1:5193';for(let i=0;i<100;i++){try{if((await fetch(base)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const browser=await chromium.launch({channel:process.env.JALWEB_BROWSER??(process.platform==='win32'?'msedge':'chromium'),headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1400,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.waitForFunction(()=>document.querySelector('#state')?.textContent==='実行できます',null,{timeout:60000});
 await page.evaluate(async()=>{const {editor}=await import('/src/main.ts');editor.setValue('public class Main {\n public static sample(I)I {\n  iload_0\n  ifle L\n  iconst_1\n  istore_1\n  iinc 1 1\n  iload_1\n  ireturn\n L:\n  iconst_0\n  ireturn\n }\n}');});
 const instruction=(target,name)=>target.locator('.view-line span').filter({hasText:new RegExp('^'+name+'$')}).first();
 await instruction(page,'iload_0').hover();await page.waitForTimeout(650);assert.equal(await page.locator('.monaco-hover:visible').count(),0);assert.equal(await page.locator('.stack-hover:visible').count(),0);
 await page.keyboard.down('Alt');const card=page.locator('.stack-hover');await card.getByText('実行前',{exact:true}).waitFor({timeout:60000});assert.ok((await card.textContent()).includes('実行後'));assert.ok(!(await card.textContent()).includes('LOCALS'));assert.deepEqual(await card.locator('.stack-hover-column code').allTextContents(),['int']);
 const a=await instruction(page,'iload_0').boundingBox(),b=await card.boundingBox();assert.ok(b.y>=a.y+a.height&&b.y-a.y-a.height<20);assert.ok(Math.abs(b.x-a.x)<30);
 await instruction(page,'istore_1').hover();await card.getByText('LOCALS',{exact:true}).waitFor();assert.match(await card.textContent(),/#1 ← スタック TOP/);await page.screenshot({path:'.cache/stack-hover-store.png'});
 await instruction(page,'iinc').hover();await card.getByText('#1 ← #1 + 1',{exact:true}).waitFor();await page.screenshot({path:'.cache/stack-hover-increment.png'});await page.keyboard.up('Alt');assert.equal(await card.isVisible(),false);
 await page.mouse.move(1100,400);await page.evaluate(async()=>{const {editor}=await import('/src/main.ts');editor.setValue('public class Main {\n public static sample(I)I {\n  iload_0\n  ireturn\n }\n}');});await page.keyboard.down('Alt');await instruction(page,'iload_0').hover();await card.getByText('実行前',{exact:true}).waitFor({timeout:15000});await page.keyboard.up('Alt');
 const tab=await page.getByRole('tab',{name:'src/Main.jal',exact:true}).boundingBox(),event=page.waitForEvent('popup');await page.mouse.move(tab.x+tab.width/2,tab.y+tab.height/2);await page.mouse.down();await page.waitForTimeout(420);await page.mouse.move(1200,350,{steps:8});await page.mouse.up();const popup=await event;popup.on('pageerror',e=>errors.push(e.message));await popup.getByRole('tab',{name:'src/Main.jal',exact:true}).waitFor();await instruction(popup,'iload_0').hover();await popup.keyboard.down('Alt');await popup.locator('.stack-hover').getByText('実行前',{exact:true}).waitFor({timeout:60000});await popup.keyboard.up('Alt');assert.equal(await popup.locator('.stack-hover').isVisible(),false);await popup.close();assert.deepEqual(errors,[]);
});
