import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {chromium} from '@playwright/test';
test('project saves and restores groups, hidden tabs, popup contents and views silently',{timeout:90000},async t=>{
 const port=5204,base=`http://127.0.0.1:${port}`,server=spawn(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port',String(port),'--strictPort'],{stdio:'pipe',windowsHide:true});t.after(()=>server.kill());for(let i=0;i<100;i++){try{if((await fetch(base)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const browser=await chromium.launch({channel:process.platform==='win32'?'msedge':'chromium',headless:true});t.after(()=>browser.close());const context=await browser.newContext({viewport:{width:1450,height:1000}});await context.route('**/runtime/**',r=>r.abort());const page=await context.newPage(),errors=[];context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{window.showDirectoryPicker=async()=>(await navigator.storage.getDirectory()).getDirectoryHandle('layout-test',{create:true});});await page.goto(base);await page.locator('#project-tab').waitFor();
 const menu=async(group,item)=>{await page.locator('#menu-'+group).click();await page.locator('#'+item).click();};const save=async()=>{await page.keyboard.press('ControlOrMeta+S');await page.waitForFunction(()=>document.querySelector('#state').textContent==='フォルダーに保存しました');};
 const disk=()=>page.evaluate(async()=>JSON.parse(await (await (await (await navigator.storage.getDirectory()).getDirectoryHandle('layout-test')).getFileHandle('project.jalprj')).getFile().then(f=>f.text())));
 for(const name of ['src/Helper.jal','src/Closed.jal']){await page.locator('#add-file').click();await page.locator('#dialog-input').fill(name);await page.locator('#dialog-ok').click();await page.getByRole('tab',{name,exact:true}).waitFor();}
 await page.getByRole('button',{name:'src/Closed.jal のタブを閉じる',exact:true}).click();
 await page.locator('#file-list button[title="src/Main.jal"]').dragTo(page.locator('.output-header'));
 await page.locator('.separator-0').focus();await page.keyboard.press('ArrowRight');await menu('view','swap-panes');
 const popupPromise=page.waitForEvent('popup');await page.locator('#instructions-tab').click({button:'right'});await page.getByRole('menuitem',{name:'小窓で開く',exact:true}).click();const popup=await popupPromise;await popup.getByRole('tab',{name:'Instructions',exact:true}).waitFor();
 const payload=await page.locator('#file-list button[title="src/Helper.jal"]').evaluate(node=>{const data=new DataTransfer();node.dispatchEvent(new DragEvent('dragstart',{bubbles:true,dataTransfer:data}));return data.getData('application/x-jalweb-tab');});await popup.locator('#file-tabs').evaluate((node,payload)=>{const data=new DataTransfer();data.setData('application/x-jalweb-tab',payload);node.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:data}));},payload);
 await popup.getByRole('tab',{name:'src/Helper.jal',exact:true}).waitFor();await popup.evaluate(async()=>{const {editor}=await import('/src/detached.ts');editor.setPosition({lineNumber:1,column:7});});await popup.getByRole('tab',{name:'Instructions',exact:true}).dragTo(popup.getByRole('tab',{name:'src/Helper.jal',exact:true}),{targetPosition:{x:2,y:12}});await save();const before=await disk();assert.equal(before.editor.windows.length,1);assert.deepEqual(before.editor.windows[0].tabs,['source:src/Helper.jal']);assert.equal(before.editor.windows[0].active,'panel:instructions');assert.equal(before.editor.windows[0].views['source:src/Helper.jal'].column,7);assert.equal(before.editor.tabs.some(t=>t.key==='source:src/Closed.jal'),false);assert.equal(before.editor.dock.swapped,true);
 await menu('file','new-project');assert.ok(popup.isClosed());
 const reopenedPromise=page.waitForEvent('popup');await menu('file','open-project');const reopened=await reopenedPromise;await reopened.getByRole('tab',{name:'Instructions',exact:true}).waitFor();await page.waitForTimeout(250);
 assert.equal(await page.locator('.output-pane').getByRole('tab',{name:'src/Main.jal',exact:true}).count(),1);assert.equal(await page.getByRole('tab',{name:'src/Closed.jal',exact:true}).count(),0);assert.equal(await page.locator('.workspace.dock-swapped').count(),1);assert.equal(await reopened.getByRole('tab',{name:'Instructions',exact:true}).getAttribute('aria-selected'),'true');
 await reopened.getByRole('tab',{name:'src/Helper.jal',exact:true}).click();assert.equal(await reopened.evaluate(async()=>(await import('/src/detached.ts')).editor.getPosition().column),7);await reopened.getByRole('tab',{name:'Instructions',exact:true}).click();await save();const after=await disk();assert.deepEqual(after.editor.order,before.editor.order);assert.deepEqual(after.editor.windows[0].order,before.editor.windows[0].order);assert.deepEqual(await reopened.locator('#file-tabs [role=tab]').allTextContents(),['Instructions','src/Helper.jal']);assert.deepEqual(after.editor.dock,before.editor.dock);assert.deepEqual(after.editor.tabs,before.editor.tabs);assert.deepEqual(after.editor.windows.map(w=>({tabs:w.tabs,panels:w.panels,active:w.active,views:w.views})),before.editor.windows.map(w=>({tabs:w.tabs,panels:w.panels,active:w.active,views:w.views})));
 // Metadata polling must not change the selected panel or restore an old layout.
 await page.locator('#console-tab').click();await page.evaluate(async()=>{const root=await (await navigator.storage.getDirectory()).getDirectoryHandle('layout-test'),h=await root.getFileHandle('project.jalprj'),p=JSON.parse(await (await h.getFile()).text());p.name='Renamed';p.editor.dock.swapped=false;const w=await h.createWritable();await w.write(JSON.stringify(p));await w.close();});await page.waitForFunction(()=>document.querySelector('#project-name').textContent==='Renamed');assert.equal(await page.locator('#console-tab').getAttribute('aria-selected'),'true');assert.equal(await page.locator('.workspace.dock-swapped').count(),1);
 await menu('file','project-properties-menu');assert.equal(await page.locator('#project-properties input').count(),1);await page.keyboard.press('Escape');
 // Restore two windows even if the first attempt is blocked; retry on real gestures.
 await menu('file','new-project');await page.evaluate(async saved=>{const root=await (await navigator.storage.getDirectory()).getDirectoryHandle('layout-test'),h=await root.getFileHandle('project.jalprj');saved.editor.windows.push({tabs:[],panels:['problems'],active:'panel:problems',views:{},left:100,top:120,width:650,height:450,wordWrap:false});const w=await h.createWritable();await w.write(JSON.stringify(saved));await w.close();window.originalOpen=window.open;window.open=()=>null;},before);
 await menu('file','open-project');await page.waitForFunction(()=>document.querySelector('.workspace.dock-swapped'));assert.equal(await page.getByRole('tab',{name:'src/Helper.jal',exact:true}).count(),1);await save();const blocked=await disk();assert.equal(blocked.editor.windows.length,2);assert.equal(await page.locator('dialog[open]').count(),0);
 await page.evaluate(()=>window.open=window.originalOpen);const firstPromise=page.waitForEvent('popup');await page.locator('#project-name').click();const first=await firstPromise;await first.getByRole('tab',{name:'Instructions',exact:true}).waitFor();const secondPromise=page.waitForEvent('popup');await page.locator('#project-name').click();const second=await secondPromise;await second.getByRole('tab',{name:'Problems',exact:true}).waitFor();await save();assert.equal((await disk()).editor.windows.length,2);assert.deepEqual(errors,[]);
});
