import { mkdir, writeFile, rm } from 'node:fs/promises';
import { readCatalogs } from './localization-catalogs.mjs';
import { checkLocalization } from './check-localization.mjs';

export async function generateLocales() {
  const { features, locales, catalogs } = await readCatalogs();
  await checkLocalization(catalogs);
  await mkdir('src/generated/locales', { recursive: true });
  for (const locale of Object.keys(locales)) {
    const imports = features.map(
      ({ directory }, i) =>
        `import catalog${i} from '${directory.replace('src/', '../../')}/${locale}.json' with { type: 'json' };`,
    );
    const body = `export default {\n${features.map((_, i) => `  ...catalog${i},`).join('\n')}\n};\n`;
    const source =
      '// Generated by scripts/generate-locales.mjs. Edit feature catalogs instead.\n' +
      imports.join('\n') +
      '\n' +
      body;
    await writeFile(`src/generated/locales/${locale}.ts`, source);
    // Remove outputs from the previous JS + separate declaration generator.
    await rm(`src/generated/locales/${locale}.js`, { force: true });
    await rm(`src/generated/locales/${locale}.d.ts`, { force: true });
  }
  await writeFile(
    'src/generated/locale-loaders.ts',
    '// Generated by scripts/generate-locales.mjs.\nexport const localeLoaders = {\n' +
      Object.keys(locales)
        .filter((l) => l !== 'ja')
        .map((l) => `  ${l}: () => import('./locales/${l}.ts'),`)
        .join('\n') +
      '\n};\n',
  );
}
